### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by stephenmc608** [456Xander/InfiniBucket#1]
Hey there.

I'm getting a crash report while loading up a custom modpack. I'm using version 1.0.1 of Infinibucket and Forge-14.23.1.2556. 

Crash Report: https://gist.github.com/stephenmc608/6d78c44d80fdb249fb68cdc4df65e4a1
Mod List: https://imgur.com/U6ctfCH

**Comment by 456Xander** [comment]
Thank you for th issue, I will look into it as fast as I can. But I currwntly have very limited time, so it could take a while.

I think this has to be a compatibility issue with another mod, as it ran fine in my tests.
It would be very helpful, if you could try to isolate the mod, with which the issue occurs, by removing mods until it starts fine. That would speed up the debugging process.

**Comment by stephenmc608** [comment]
I tried disabling every mod, except for Infinibucket and I still got the same crash report.

Crash Report 2: https://gist.github.com/stephenmc608/3bd1e7f57df2feba4ec6ef4bac666b46
Mod List: https://i.imgur.com/wuK8loK.png (As you can see, all mods are disabled, except for Infinibucket)

**Comment by 456Xander** [comment]
That is really strange, I tested it with the same forge version on my PC and it runs fine.
Have you already tried starting it with a different forge version for 1.12.2?

**Comment by 456Xander** [comment]
Ok, I haven't found the bug, but I could fix it. I never could reproduce the bug, because I worked with a freshly compiled mod jar from the project, however the file I uploaded to curse must somehow be corrupted. It almost looks as if it wasn't reobfuscated. The strange thing is, that I have not changed any code since then, but the working mod is about 10% larger in size...
I'll just upload the working one as 1.0.2 and mark the 1.0.1 as bugged.
